# Site settings
title: Back That Elf Up
author: Tristan J. Tarwater
email: 

keywords: fantasy, slice of life, author, speculative fiction, comics, webcomics, RPGs
description: > # this means to ignore newlines until "baseurl:"
  The home of Tristan J. Tarwater - novelist, comic writer, and tabletop RPG freelancer.

baseurl: https://www.backthatelfup.com
url: /
#url: localhost:4000

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems:
  - octopress-autoprefixer
  
destination: _site

# Compress our Css
sass:
  style: :compressed

permalink: /blog/:year/:title/

#################################################
####CUSTOM

# Set default header image
header: no
header_sm:
header_med:
header_large:
header_xl:

## Thumbnailer taken from https://github.com/chrisanthropic/jekyll-minimagick

# Autogenerate thumbs for comics
mini_magick:

#Create Thumbs for all book covers
    thumbnail:
      source: images/books/
      destination: /images/books/thumbs
      resize: "76x122^"


    thumbnail2:
      source: images/posts/
      destination: /images/posts/thumbs
      resize: "145"
      

#### SEO Stuff
# Google Analytics
# google_universal_analytics: UA-22568632-1
# google_universal_analytics_cookiedomain: backthatelfup.com


# Facebook Tracking Pixel
# fb_tracking_pixel: 1381762635484775

# Facebook Opengraph
facebook_user: BackThatElfUp
facebook_app_id: 212934732101925
facebook_locale: en_US
facebook_page: https://www.facebook.com/BackThatElfUp
facebook_image: https://www.backthatelfup.com/images/BTEUlogo-med-200x200.png

# Twitter Cards
twitter_user: backthatelfup
twitter_card: true
twitter_image: https://www.backthatelfup.com/images/BTEUlogo-med-200x200.png

# Disqus Comments
disqus_short_name: backthatelfup
