baseurl = "https://backthatelfup.com/"
languageCode = "en-us"
title = "Back That Elf Up"
theme = "slim-pickins"
Paginate = 10


[taxonomies]
  category = "categories"

[params]
  header = ""

[[menu.main]]
  name = "blog"
  identifier = "blog"
  url = "/blog/"
  weight = 2

[[menu.socials]]
  name = "twitter"
  identifier = "twitter"
  url = "https://www.twitter.com/backthatelfup"
  weight = 1

[[menu.socials]]
  name = "facebook"
  identifier = "facebook"
  url = "https://www.facebook.com/backthatelfup"
  weight = 3

[[menu.socials]]
  name = "feed"
  identifier = "feed"
  url = "/index.xml"
  weight = 4
