[build]
  publish = "public"
  command = "hugo"

[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_VERSION = "0.41"
    HUGO_ENV = "production"
  [context.deploy-preview.environment]
    HUGO_VERSION = "0.41"
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.41"
