[build]
  publish = "public"
  command = "hugo"

[context.production]
  command = "hugo"
  [context.production.environment]
    HUGO_VERSION = "0.42.1"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.42.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.42.1"
  command = "hugo"
  publish = "public"
  HUGO_BASEURL = "https://hugo.backthatelfup.com/"
